export const UI_TEXT = {
  appName: "Orçamento",
  appSubtitle: "Liquidez e património",
  metadataTitle: "Orçamento e património",
  metadataDescription: "Aplicação pessoal para controlo mensal de orçamento e património.",
  navigation: {
    budget: "Orçamento",
    history: "Histórico",
    accounts: "Contas",
    recurring: "Débitos directos",
    investments: "Investimentos",
    igcp: "IGCP",
    settings: "Configurações",
    logout: "Terminar sessão",
  },
  summary: {
    currentLiquidity: "Liquidez actual",
    finalLiquidity: "Liquidez final",
    forecasts: "Previsões",
    creditCardDebt: "Dívida dos cartões",
    investments: "Investimentos",
    netWorth: "Património líquido",
  },
  budget: {
    monthlyBudget: "Orçamento mensal",
    previousMonth: "Mês anterior",
    month: "Mês",
    nextMonth: "Mês seguinte",
    currentMonth: "Mês actual",
    monthlyTable: "Tabela mensal",
    rowHeader: "Linha",
    heritageSection: "Património",
    investments: "Investimentos",
    netWorth: "Património líquido",
  },
} as const;

export const PRIMARY_UI_TITLES = [
  UI_TEXT.appName,
  UI_TEXT.appSubtitle,
  UI_TEXT.metadataTitle,
  UI_TEXT.navigation.history,
  UI_TEXT.navigation.recurring,
  UI_TEXT.navigation.igcp,
  UI_TEXT.navigation.settings,
  UI_TEXT.summary.forecasts,
  UI_TEXT.summary.creditCardDebt,
  UI_TEXT.summary.netWorth,
  UI_TEXT.budget.monthlyBudget,
  UI_TEXT.budget.previousMonth,
  UI_TEXT.budget.currentMonth,
] as const;
